/**
 * RCB standard canvas API — Document facade.
 * Prefer: `import { … } from '@/components/rcb/api'`
 */
export {
  DEFAULT_CANVAS,
  A4_PORTRAIT,
  createBareDocument,
  createEmptyDocument,
  normalizeDocument,
  addNodeToDocument,
  addNodesToDocument,
  updateNodeInDocument,
  updateNodesInDocument,
  removeNodesFromDocument,
  reorderNodesInDocument,
  mergeImportedIntoDocument,
  listSceneNodes,
  setDocumentSize,
  setDocumentCanvasMeta,
  getActivePage,
  syncRootChildren,
  ensureDocumentContentOnCanvas,
  stackFrameKey,
  stackNodeKey,
  parseStackKey,
  reconcileStackOrder,
  stackZIndex,
  maxDocumentStackZ,
  maxArtboardPlateStackZ,
  buildNodeStackZMap,
  buildUnifiedHitZMap,
  selectionPaintZIndex,
  nodePaintZIndex,
  worldNodeStacksAboveAnyFrame,
  listSingleSelectionPaintRaiseNodeIds,
  isSingleStackSelection,
  mergeNodePatch,
  type SceneNodePatch,
  type DocumentCanvasMetaPatch,
} from '@/components/rcb/scene/document/sceneDocument';

export {
  validateSceneDocument,
  parseAndValidateSceneJson,
  coerceSceneDocumentInput,
  SceneDocumentSchema,
  SceneNodeSchema,
  type SceneDocument,
  type SceneNode,
  type SceneNodeInput,
  type SceneNodeAttrs,
  type SceneDeltaSet,
  type ScenePage,
} from '@/components/rcb/sceneNode';
